### PR TITLE
MercadoPago v3.2.0 integration

### PR DESCRIPTION
**Pull request by JonatanSalas**
**THIS PR IS ONLY FOR TRACKING, I HAVEN'T FINISHED TO INTEGRATE WITH IOS.**

This PR closes the issue #11.

I'm working on MercadoPago v3.2.0 integration for Android/IOS. The new SDK have added a lot of new improvements to the way it's working. Some of the improvements are: 

- Better back button handling, for the case of user cancellation. 
- More decouple logic so you're able to create your own checkout experience.
- Added two ways to start checkout, one for Payment (intended for simple checkout) and one for PaymentData (intended for custom checkout through MP Connect/MarketPlace). 

My first attempt to integrate this SDK version it's to resolve the 3rd case of improvement, for those who intended to use the Checkout for a simple use case, and also, those who use MP Connect/MarketPlace. 

Also I have been working on the following new features: 
- Support for DecorationPreference.
- Better Error Handling, by bubbling the error from the native code, to the JS code. 

There're a lot of new things that have been added on the new MP SDK, but I think this is the basic. 

**If you want to review my code, you're really welcome.**

### CODE REVIEW

**Comment by JonatanSalas** [comment]
@scarmuega The Checkout in IOS now it's working in the example App. 

There was a trouble related to UINavigationController. When I was casting the rootViewController in the shared AppDelegate, the rootViewController seems to be an instance of UIViewController instead of UINavigationController. 

I have solved this, by modifying the AppDelegate from the example app, and generating a UINavigationController instance from the rootViewController instance, and attaching it to the window.rootViewController, so it's available from the AppDelegate. 

**I'm not sure at all if I'm doing the right thing, so I would be glad if someone review my IOS code and the example app.** 

Also, I have another issue, but it's mine, I'm still working on the PaymentData callback management. It's not firing correctly. When I'm done with this issue, this PR must be ready to be merged. 

I will modify part of the **README.md** to tell how to use the new version. This will be included in the PR anyway!

**Comment by JonatanSalas** [comment]
Another thing I will modify in the near future its the IOS related code, so everything it's solved through **Swift 3.** There's already support for react-native to doing it!

**Comment by JonatanSalas** [comment]
@scarmuega PR is able to merge! Could you review please?

**Comment by scarmuega** [comment]
@JonatanSalas why did you close? something pending?

**Pull request closed without merging**
