### PR TITLE
Fix CheckoutMercadoPagoModule undefined is not an Object in Example App

### PR DESCRIPTION
**Pull request by JonatanSalas**
This PR is intended to fix issue #5. 

I have made a deeper dive on the root causes of what the problems was. After searching I found a lot of guys recommendations to run *react-native upgrade* in order to match the latest versions of react-native folder structure. I have updated the example app, so now, if you run it, you will see that it launches correctly the MercadoPago checkout. 

Also, I have made a little modifications to the example app. Little ones, like modify handlePress method to a class property, and remove lambda expression from render return method (this avoid the app to re render due to function creation inside return statement). 

And another modification was to put credentials inside app.json. 

I think that's all. Feel free to probe it, and let's review this. I will collaborate if something needs to be modified. **This fixes aren't related to the library, they're related to the example app.**

PD: I add here an screenshot of the MercadoPago checkout

captura de pantalla 2017-06-01 a la s 21 50 37

### CODE REVIEW

**Comment by pablomayobre** [comment]
Note that this overrides #4 since it upgrades Android API to 25 (while the aforementioned PR only does up to 24)

In another note, you made so many changes that it is kinda hard to track what actually fixed the issue #5 

I would merge this anyway though, since it upgrades the structure of the project, fixes a bug and updates to latest Android SDK versions

**Comment by JonatanSalas** [comment]
@Positive07 If you read my first comment you'll note that I haven't touched anything related to the library. It seems that the issue was related to older config on the example react-native project.

**Comment by scarmuega** [comment]
@JonatanSalas thank you very much for all the hard work. I'll merge the PR and publish to NPM.

**Comment by JonatanSalas** [comment]
@scarmuega You're welcome! This library is simplifying us to integrate *mercadopago* in our react-native apps, so thank you for giving the library to the community!

**Pull request merged**
